changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: Security
      labels:
        - security
    - title: Release tooling
      labels:
        - release
        - automation
    - title: Documentation
      labels:
        - documentation
    - title: Other changes
      labels:
        - "*"
